=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 5 - XSD/Exercicis XSD II/Exercici 4/Cojita_Stefan_Exercici_4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="subasta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="objeto" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="propietario" type="xs:string"/>
                            <xs:element name="precio_salida">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="6"/>   
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="precio_minimo" minOccurs="0">
                                <xs:simpleType>
                                    <xs:restriction base="xs:decimal">
                                        <xs:totalDigits value="6"/>   
                                        <xs:fractionDigits value="2"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 5 - XSD/Exercicis XSD II/Exercici 4/Cojita_Stefan_Exercici_4.xml
<?xml version="1.0" encoding="UTF-8"?>
<subasta xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Cojita_Stefan_Exercici_4.xsd">
    <objeto>
        <propietario> Pedro Rodr√≠guez </propietario>
        <precio_salida> 10.42 </precio_salida>
        <precio_minimo> 3.42 </precio_minimo>
    </objeto>
    <objeto>
        <propietario> Pablo Manrique </propietario>
        <precio_salida> 95.75 </precio_salida>
    </objeto>
</subasta>
