=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 4 - DTD/Exercicis DTD III/Exercici_16/Cojita_Stefan_Exercici_16.dtd
<!ELEMENT informe (cabecera, datos)>
<!ELEMENT cabecera (descripcion, fecha)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT datos (region+)>
<!ELEMENT region (nombre, trimestre*, libros_vendidos*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT trimestre (#PCDATA)>
<!ELEMENT libros_vendidos (#PCDATA)>

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 3 - XML/Exercicis DTD III/Exercici 16/Cojita_Stefan_Exercici_16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informe SYSTEM "Cojita_Stefan_Exercici_16.dtd">
<informe>
    <cabecera>
        <descripcion> Informe regional de ventas </descripcion>
        <fecha> 30/12/2009 </fecha>
    </cabecera>
    <datos>
        <region>
            <nombre> Norte </nombre>
            <trimestre> 1 </trimestre>
            <trimestre> 2 </trimestre>
            <trimestre> 3 </trimestre>
            <trimestre> 4 </trimestre>
            <libros_vendidos> 24000 </libros_vendidos>
            <libros_vendidos> 38600 </libros_vendidos>
            <libros_vendidos> NO_INFO </libros_vendidos>
            <libros_vendidos> NO_INFO </libros_vendidos>
        </region>
        <region>
            <nombre> Centro </nombre>
            <trimestre> 1 </trimestre>
            <trimestre> 2 </trimestre>
            <trimestre> 3 </trimestre>
            <trimestre> 4 </trimestre>
            <libros_vendidos> NO_INFO </libros_vendidos>
            <libros_vendidos> 16080 </libros_vendidos>
            <libros_vendidos> 25000 </libros_vendidos>
            <libros_vendidos> 29000 </libros_vendidos>
        </region>
        <region>
            <nombre> Sur </nombre>
            <trimestre> 1 </trimestre>
            <trimestre> 2 </trimestre>
            <trimestre> 3 </trimestre>
            <trimestre> 4 </trimestre>
            <libros_vendidos> 27000 </libros_vendidos>
            <libros_vendidos> 31400 </libros_vendidos>
            <libros_vendidos> 40100 </libros_vendidos>
            <libros_vendidos> 30000 </libros_vendidos>
        </region>
    </datos>
</informe>

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 3 - XML/Exercicis DTD III/Cojita_Stefan_Exercici_16.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informe SYSTEM "Cojita_Stefan_Exercici_16.dtd">
<informe>
    <cabecera>
        <descripcion> Informe regional de ventas </descripcion>
        <fecha> 30/12/2009 </fecha>
    </cabecera>
    <datos>
        <region>
            <nombre> Norte </nombre>
            <trimestre> 1 </trimestre>
            <trimestre> 2 </trimestre>
            <trimestre> 3 </trimestre>
            <trimestre> 4 </trimestre>
        </region>
        <region>
            <nombre> Centro </nombre>
            <trimestre> 1 </trimestre>
            <trimestre> 2 </trimestre>
            <trimestre> 3 </trimestre>
            <trimestre> 4 </trimestre>
        </region>
        <region>
            <nombre> Sur </nombre>
            <trimestre> 1 </trimestre>
            <trimestre> 2 </trimestre>
            <trimestre> 3 </trimestre>
            <trimestre> 4 </trimestre>
        </region>
    </datos>
</informe>
