=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 3 - XML/Exercicis DTD I/Cojita_Stefan_Exercici_2.dtd
<!ELEMENT programa (pedido*)>
<!ELEMENT pedido (numero_serie, cantidad, peso?)>
<!ELEMENT numero_serie (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT peso (#PCDATA)>

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 4 - DTD/Exercicis DTD I/Cojita_Stefan_Exercici_2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE programa SYSTEM "./Cojita_Stefan_Exercici_2.dtd">
<programa>
    <pedido>
        <numero_serie> 567-453-AA-121-AA </numero_serie>
        <cantidad> 2 </cantidad>
    </pedido>
    <pedido>
        <numero_serie> 123-212-BB-142-BB </numero_serie>
        <cantidad> 1 </cantidad>
        <peso> 5 </peso>
    </pedido>
</programa>
