=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 4 - DTD/Exercicis DTD IV/Exercici 3/Cojita_Stefan_Exercici_3.dtd
<!ELEMENT concesionario (modelo*)>
<!ELEMENT modelo (descripcion, motor?, consumo*, modelos_relacionados*)>
<!ATTLIST modelo referencia ID #REQUIRED>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT motor (referencia_modelo_relacionado+, tipo_motor, potencia)>
<!ELEMENT referencia_modelo_relacionado (#PCDATA)>
<!ELEMENT tipo_motor (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT consumo (velocidad, valor)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT valor (#PCDATA)>
<!ELEMENT modelos_relacionados (#PCDATA)>

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 4 - DTD/Exercicis DTD IV/Exercici 3/Cojita_Stefan_Exercici_3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE concesionario SYSTEM "Cojita_Stefan_Exercici_3.dtd">
<concesionario>
    <modelo referencia= "n556">
        <descripcion>No disponible</descripcion>
        <motor>
            <referencia_modelo_relacionado />
            <tipo_motor>1.998cc 16v</tipo_motor>
            <potencia>128 CV</potencia>
        </motor>
        <consumo>
            <velocidad>11</velocidad>
            <valor>100 km</valor>
        </consumo>
        <consumo>
            <velocidad>120</velocidad>
            <valor>10 km</valor>
        </consumo>
    </modelo>
    <modelo referencia="n555">
        <descripcion>No disponible</descripcion>
        <motor>
            <referencia_modelo_relacionado>444, 556</referencia_modelo_relacionado>
            <tipo_motor>2.000cc 16v</tipo_motor>
            <potencia>128 CV</potencia>
        </motor>
        <modelos_relacionados>444 556</modelos_relacionados>
    </modelo>
    <modelo referencia="n557">
        <descripcion>No disponible</descripcion>
    </modelo>

    <modelo referencia="n154">
        <descripcion>No disponible</descripcion>
        <modelos_relacionados>555 154</modelos_relacionados>
    </modelo>
    <modelo referencia="n444">
        <descripcion>Este modelo tiene un motor 2.000cc 16v de cuatro cilindros con 128 CV. Dispone
            de cambio manual. El consumo medio de este monovolumen es 11 a los 100 km. El precio
            base es de 2.500.000.</descripcion>
        <motor>
            <referencia_modelo_relacionado>555</referencia_modelo_relacionado>
            <tipo_motor>2.000cc 16v</tipo_motor>
            <potencia>128 CV</potencia>
        </motor>
        <consumo>
            <velocidad>11</velocidad>
            <valor>100 km</valor>
        </consumo>
        <modelos_relacionados>555 154</modelos_relacionados>
    </modelo>
</concesionario>
