=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 5 - XSD/Exercicis XSD III/adsl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="conexions_ADSL">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="oferta" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nom_compania" type="xs:string"/>
                            <xs:element name="velocitat_transferencia">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="pujada" type="xs:decimal"/>
                                        <xs:element name="baixada" type="xs:decimal"/>
                                    </xs:sequence>
                                    <xs:attribute name="unitat" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="preu">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="alta">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="preu_alta" type="xs:decimal" minOccurs="0"/>
                                                    <xs:element name="permanencia_alta" minOccurs="0">
                                                        <xs:complexType>
                                                            <xs:attribute name="tiempo" type="xs:string"/>
                                                            <xs:attribute name="quantitat" type="xs:int"/>
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="gratis" type="xs:string"/>
                                                <xs:attribute name="permanencia" type="xs:string"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="linea" type="xs:decimal"/>
                                        <xs:element name="promocio" minOccurs="0" maxOccurs="unbounded">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="promocio_preu" type="xs:decimal"/>
                                                </xs:sequence>
                                                <xs:attribute name="fins" type="xs:date"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="mensual" type="xs:decimal"/>
                                        <xs:element name="total_mensual" type="xs:decimal"/>
                                        <xs:element name="extres" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                    <xs:attribute name="moneda" type="xs:string"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int"/>
                        <xs:attribute name="nom" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>   
    </xs:element>
</xs:schema>

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 5 - XSD/Exercicis XSD III/adsl.xml
<?xml version="1.0" encoding="UTF-8"?>
<conexions_ADSL xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="adsl.xsd">
    <oferta id="1" nom="Arrakis BT Go">
          <nom_compania>Arrakis</nom_compania>
     
          <velocitat_transferencia unitat="Mbps">
            <pujada>0</pujada>
            <baixada>6</baixada>
          </velocitat_transferencia>
         
          <preu moneda="Euro">
         
                <alta gratis="Si" permanencia="No"/>
                    <!--<preu_alta></preu_alta>
                    <permanencia_alta></permanencia_alta>-->
                <linea>13.97</linea>
                <mensual>36.50</mensual>
                <total_mensual>50.47</total_mensual>
               
          </preu>
 
    </oferta>
 
    <oferta id="2" nom="Arrakis eOficina">

          <nom_compania>Arrakis</nom_compania>
       
          <velocitat_transferencia unitat="Mbps">
            <pujada>0</pujada>
            <baixada>6</baixada>
          </velocitat_transferencia>
         
          <preu moneda="Euro">
         
                <alta gratis="Si" permanencia="No"/>
                      <!--<preu_alta></preu_alta>
                    <permanencia_alta></permanencia_alta>-->
                <linea>13.97</linea>
                <mensual>59.90</mensual>
                <total_mensual>73.87</total_mensual>
               
          </preu>
 
    </oferta>
   
    <oferta id="3" nom="ADSL 1 Mega + Llamadas gratis con Línea Jazztel ">

          <nom_compania>Jazztel</nom_compania>
         
          <velocitat_transferencia unitat="Mbps">
            <pujada>0.512</pujada>
            <baixada>1</baixada>
          </velocitat_transferencia>
         
          <preu moneda="Euro">
         
                <alta gratis="Si" permanencia="No"/>
                    <!--<preu_alta></preu_alta>
                    <permanencia_alta></permanencia_alta>-->
                <linea>0</linea>
                <promocio fins="2014-01-01">
                <promocio_preu>15.94</promocio_preu>
                </promocio>
                <mensual>19.95</mensual>
                <total_mensual>19.95</total_mensual>
               
          </preu>
 
    </oferta>
   
   
    <oferta id="4" nom="Movistar ADSL 10 Mb ">

          <nom_compania>Movistar</nom_compania>
       
          <velocitat_transferencia unitat="Mbps">
            <pujada>6</pujada>
            <baixada>10</baixada>
          </velocitat_transferencia>
         
          <preu moneda="Euro">
         
                <alta gratis="Si" permanencia="Si">
                    <!--<preu_alta></preu_alta>-->
                    <permanencia_alta tiempo="meses" quantitat="12"/>
                </alta>
                <linea>13.97</linea>
                <promocio fins="2014-01-01">
                  <promocio_preu>24.90</promocio_preu>
                </promocio>
                <promocio fins="2014-06-01">
                  <promocio_preu>26.90</promocio_preu>
                </promocio>
                <mensual>29.90</mensual>
                <total_mensual>43.87</total_mensual>
               
          </preu>
 
    </oferta>
   
    <oferta id="5" nom="Movistar Fibra Óptica 100/10 Mb">

          <nom_compania>Movistar</nom_compania>
       
          <velocitat_transferencia unitat="Mbps">
            <pujada>10</pujada>
            <baixada>20</baixada>
          </velocitat_transferencia>
         
          <preu moneda="Euro">
         
                <alta gratis="Si" permanencia="Si">
                    <!--<preu_alta></preu_alta>-->
                    <permanencia_alta tiempo="meses" quantitat="12"/>
                </alta>
                <linea>13.97</linea>
                <promocio>
                <promocio_preu>39.90</promocio_preu>
                </promocio>
                <mensual>39.90</mensual>
                <total_mensual>53.87</total_mensual>
               
          </preu>
 
    </oferta>
 
        <oferta id="6" nom="ASDL Máxima Velocidad">

          <nom_compania>Orange </nom_compania>
         
          <velocitat_transferencia unitat="Mbps">
            <pujada>0.512</pujada>
            <baixada>6</baixada>
          </velocitat_transferencia>
         
          <preu moneda="Euro">
         
                <alta gratis="Si" permanencia="Si">
                    <!--<preu_alta></preu_alta>-->
                    <permanencia_alta tiempo="meses" quantitat="18"/>
                </alta>
                <linea>13.97</linea>
                <promocio fins="2014-01-01">
                <promocio_preu>11.95</promocio_preu>
                </promocio>
                <mensual>15.95</mensual>
                <total_mensual>29.92</total_mensual>
                <extres>Router Wifi</extres>
                <extres>Alta gratis online</extres>
               
          </preu>
 
    </oferta>


</conexions_ADSL>
