=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 4 - DTD/Exercicis DTD II/Cojita_Stefan_Exercici_5.dtd
<!ELEMENT listado (futuros+, divisas+, bonos+, letras+)>
<!ELEMENT futuros (producto, mercado?, (madrid|ny|frankurt|tokyo))>
<!ELEMENT divisas (nombre, tipocambio+, (madrid|ny|frankurt|tokyo))>
<!ELEMENT bonos ((madrid|ny|frankurt|tokyo), vdeseado, vaminimo, vmaximo)>
<!ELEMENT letras (tipointeres, (espana|eeuu|alemania|japon))>
<!ELEMENT producto (#PCDATA)>
<!ELEMENT mercado (#PCDATA)>
<!ELEMENT madrid EMPTY>
<!ELEMENT ny EMPTY>
<!ELEMENT frankurt EMPTY>
<!ELEMENT tokyo EMPTY>
<!ELEMENT espana EMPTY>
<!ELEMENT eeuu EMPTY>
<!ELEMENT alemania EMPTY>
<!ELEMENT japon EMPTY>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipocambio (#PCDATA)>
<!ELEMENT vdeseado (#PCDATA)>
<!ELEMENT vaminimo (#PCDATA)>
<!ELEMENT vmaximo (#PCDATA)>
<!ELEMENT tipointeres (#PCDATA)>
<!ATTLIST futuros precio CDATA #REQUIRED>
<!ATTLIST divisas precio CDATA #REQUIRED>
<!ATTLIST bonos precio CDATA #REQUIRED>
<!ATTLIST letras precio CDATA #REQUIRED>
<!ATTLIST divisas estable (si|no) #IMPLIED>
<!ATTLIST bonos estable (si|no) #IMPLIED>

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 3 - XML/Exercicis DTD II/Cojita_Stefan_Exercici_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE listado SYSTEM "./Cojita_Stefan_Exercici_5.dtd">
<listado>
    <futuros precio="45">
        <producto> Sopa de pollo </producto>
        <mercado> Raizu </mercado>
        <tokyo></tokyo>
    </futuros>
    <divisas precio="55" estable="si">
        <nombre> Nassambund </nombre>
        <tipocambio> cc </tipocambio>
        <ny></ny>
    </divisas>
    <bonos precio="200" estable="no">
        <frankurt></frankurt>
        <vdeseado> 25 </vdeseado>
        <vaminimo> 2 </vaminimo>
        <vmaximo> 27 </vmaximo>
    </bonos>
    <letras precio="142">
        <tipointeres> Compuesto </tipointeres>
        <espana></espana>
    </letras>
</listado>
