=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 4 - DTD/Exercicis DTD IV/Exercici 5/Cojita_Stefan_Exercici_5.dtd
<!ELEMENT videoclub (factura+)>
<!ELEMENT factura (cliente, datos_factura)>
<!ELEMENT cliente (nombre, apellidos, dni, telefono, idCliente)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellidos (#PCDATA)>
<!ELEMENT dni (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT idCliente (#PCDATA)>
<!ELEMENT datos_factura (resguardo, (alquileres | compras | (alquileres, compras)))>
<!ELEMENT resguardo (formaPago, importeTotal)>
<!ELEMENT formaPago (#PCDATA)>
<!ELEMENT importeTotal (#PCDATA)>
<!ELEMENT alquileres (fechaDevolucion, pelicula+)>
<!ELEMENT compras ((dvd | cinta)+)>
<!ELEMENT fechaDevolucion (#PCDATA)>
<!ELEMENT pelicula (titulo, genero, duracion, actores, idPelicula, valoracion, caratula?)>
<!ELEMENT actores (actor1, actor2, actor3)>
<!ELEMENT actor1 (#PCDATA)>
<!ELEMENT actor2 (#PCDATA)>
<!ELEMENT actor3 (#PCDATA)>
<!ELEMENT idPelicula (#PCDATA)>
<!ELEMENT valoracion (#PCDATA)>
<!ELEMENT caratula (#PCDATA)>
<!ELEMENT dvd (titulo, fecha_salida, extras)>
<!ELEMENT fecha_salida (#PCDATA)>
<!ELEMENT extras (#PCDATA)>
<!ELEMENT cinta (titulo, formato, rebobinada)>
<!ELEMENT formato (#PCDATA)>
<!ELEMENT rebobinada (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ATTLIST caratula archivo CDATA "caratulas/">

=== 1DAMSCojita/SSD_clase/LMSGI/Unidad 4 - DTD/Exercicis DTD IV/Cojita_Stefan_Exercici_5.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE videoclub SYSTEM "Cojita_Stefan_Exercici_5.dtd">
<videoclub>
    <factura>
        <cliente>
            <nombre> Stefan </nombre>
            <apellidos> Cojita </apellidos>
            <dni> Y4480231P </dni>
            <telefono> 123456789 </telefono>
            <idCliente> 5 </idCliente>
        </cliente>
        <datos_factura>
            <resguardo>
                <formaPago> Tarjeta de crédito </formaPago>
                <importeTotal> 11.99 </importeTotal>
            </resguardo>
            <alquileres>
                <fechaDevolucion> 2024-04-10 </fechaDevolucion>
                <pelicula>
                    <titulo> American Pysco Zu </titulo>
                    <genero> Acción </genero>
                    <duracion> 140 </duracion>
                    <actores>
                        <actor1> Patricio </actor1>
                        <actor2> Gustavo </actor2>
                        <actor3> Felipe </actor3>
                    </actores>
                    <idPelicula> 001 </idPelicula>
                    <valoracion> 9.1 </valoracion>
                    <caratula> c0360.jpg </caratula>
                </pelicula>
            </alquileres>
        </datos_factura>
    </factura>
    <factura>
        <cliente>
            <nombre> David </nombre>
            <apellidos> Gomila </apellidos>
            <dni> 231322328S </dni>
            <telefono> 987654321 </telefono>
            <idCliente> 2 </idCliente>
        </cliente>
        <datos_factura>
            <resguardo>
                <formaPago> Efectivo </formaPago>
                <importeTotal> 17.99 </importeTotal>
            </resguardo>
            <alquileres>
                <fechaDevolucion> 2024-03-06 </fechaDevolucion>
                <pelicula>
                    <titulo> La Pusitania </titulo>
                    <genero> Acción </genero>
                    <duracion> 180 </duracion>
                    <actores>
                        <actor1> Zero </actor1>
                        <actor2> Victor </actor2>
                        <actor3> Luis </actor3>
                    </actores>
                    <idPelicula> 002 </idPelicula>
                    <valoracion> 8.7 </valoracion>
                    <caratula> c1201.jpg </caratula>
                </pelicula>
            </alquileres>
        </datos_factura>
    </factura>
</videoclub>
